[package]
name = "telemetry"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
axum = "0.8.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4", "serde"] }
